CREATE DATABASE IF NOT EXISTS gameapp;
USE gameapp;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  favorites JSON DEFAULT NULL,
  platform VARCHAR(50) NOT NULL DEFAULT 'all',
  theme VARCHAR(20) NOT NULL DEFAULT 'dark',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
